analytics: {}
color:
  brandColors:
    - '#98C8B0'
    - '#00A050'
    - '#68B090'
    - '#C81838'
    - '#F06860'
  brandStrength: 0.13809991953894496
  lightness: 0.5609033450018615
  rhythmicContrast: 0.6244354273658246
  saturation: 0.3245078835170716
cta: {}
layout_spectrum: 0.577302
name: unbundled
opengraph: {}
purpose: []
typography_spectrum: 0.735358928097412
